food = input("Name a food:")
plant = input("Name a type of plant:")
cooking = input("Name a method of cooking:")
ruined = input("What word describes burned food?")
diy = input("Name a DIY item:")
print("MENU")
print(cooking, food, "with", ruined, plant, "on a bed of", diy)
