print("whats your name")
name = input()
print("whats your favorite food?")
food = input()
print("whats your favorite music?")
music = input()
print("where do you live?")
location = input()
print ("you are", name ,) 
print("you are probably hungry for", food)
print("and you are definitely getting your groove on to", music)
print("living in the amazing", location)
print("damn youre a pre chill n nonchalant person icl")
